name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.check.outputs.release }}
      version: ${{ steps.check.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: check
        shell: bash
        run: |
          MESSAGE=$(git log -1 --pretty=%B)

          if [[ "$MESSAGE" == v* ]]; then
            echo "release=true" >> $GITHUB_OUTPUT
            echo "version=$MESSAGE" >> $GITHUB_OUTPUT
          else
            echo "release=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: needs.check.outputs.release == 'true'

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Check Rust
        working-directory: src-tauri
        run: cargo check

      - name: Build
        run: bun tauri build

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check.outputs.version }}
          name: Monochrome ${{ needs.check.outputs.version }}
          files: |
            src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}