name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            jq \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - uses: dtolnay/rust-toolchain@stable

      - id: version
        shell: bash
        run: |
          VERSION="v$(jq -r '.version' src-tauri/tauri.conf.json)"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - run: cargo install tauri-cli

      - working-directory: src-tauri
        run: cargo check

      - run: bun tauri build

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
          files: |
            src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}